### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by KysonLai** [Jack-Cherish/python-spider#34]
Traceback (most recent call last):
  File "D:/Files/Python Practice/test/test.py", line 160, in <module>
    douyin.run()
  File "D:/Files/Python Practice/test/test.py", line 125, in run
    video_names, video_urls, share_urls, nickname = self.get_video_urls(user_id)
  File "D:/Files/Python Practice/test/test.py", line 46, in get_video_urls
    uid = html['user_list'][0]['user_info']['uid']
KeyError: 'user_list'

**Comment by KysonLai** [comment]
你好，请问这样的情况怎么解决？

**Comment by Jack-Cherish** [comment]
@KysonLai 抖音这个还没更新，增加了参数验证。
