### ISSUE TITLE
出错了呀KeyError: 'aweme_list'`

### ISSUE THREAD

**Issue by tianyi725** [Jack-Cherish/python-spider#72]
`解析视频链接中
Traceback (most recent call last):
  File "douyin_appsign.py", line 325, in <module>
    douyin.run()
  File "douyin_appsign.py", line 283, in run
    video_names, video_urls, share_urls, nickname = self.get_video_urls(user_id,
 type_flag)
  File "douyin_appsign.py", line 194, in get_video_urls
    for each in html['aweme_list']:
KeyError: 'aweme_list'`

出错了。。。。

**Comment by tianyi725** [comment]
规则好像改了

**Comment by KennyLiu25775** [comment]
都散了吧 appsign 关了 谁也别想爬了
