### ISSUE TITLE
抖音的爬虫可以吗

### ISSUE THREAD

**Issue by Break369** [Jack-Cherish/python-spider#98]
Traceback (most recent call last):
  File "douyin/douyin.py", line 195, in <module>
    douyin.run()
  File "douyin/douyin.py", line 153, in run
    video_names, video_urls, share_urls, nickname = self.get_video_urls(user_id, type_flag)
  File "douyin/douyin.py", line 44, in get_video_urls
    tac = _tac_re.search(share_user.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Jack-Cherish** [comment]
@Break369 失效了。
